version: "3.4"

volumes:
  persist:

services:
  ring_api:
    build: ./build
    env_file: .env
    volumes:
      - ./build/entrypoint.sh:/entrypoint.sh:ro
      - ./build/app:/app
      - persist:/persist
